### ISSUE TITLE
Search stops in a street

### ISSUE THREAD

**Issue by helloIAmPau** [TinyBoxDev/androclick-server#5]
An user makes a GET request on `/streets/:cityname/:streetname` in order to obtain the list of stops placed in that street. The response is shaped as JSON array similar to the following:

``` javascript
[
  ...,
  {
    stopname: "stop name",
    stopnumber: 9999,
    position: {
      lat: 99.9999,
      lon: 99.9999
    }
  },
  ...
]
```

**Comment by b3by** [comment]
About time!
